spring:
  application:
    name: server-common
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://jlht.icu:3308/readwrite_splitting_db?allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true
    proxy-target-class: true
mybatis:
  type-aliases-package: cn.fan
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:
    name: server-common
  config-center:
    address: zookeeper://jlht.icu:2181