spring:
  application:
    name: debug-data
  rabbitmq:
    addresses: 786793.top:5672
    publisher-returns: true
    username: admin
    password: admin
  data:
    mongodb:
      uri: mongodb://admin:admin@786793.top:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
      database: debugger_music
dubbo:
  config-center:
    address: zookeeper://786793.top:2181