spring:
  application:
    name: debug-data
  rabbitmq:
    addresses: jlht.icu:5672
    publisher-returns: true
    username: admin
    password: admin
    listener:
      direct:
        retry:
          enabled: true
          max-attempts: 3
      simple:
        concurrency: 9
        prefetch: 10
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  aop:
    auto: true
    proxy-target-class: true
dubbo:
  config-center:
    address: zookeeper://150.158.213.141:2181
qm-api-host: 150.158.213.141