spring:
  application:
    name: debug-data
    workerId: 1
    datacenterId: 1
  rabbitmq:
    addresses: jlht.icu:5672
    publisher-returns: true
    username: admin
    password: admin
    listener:
      direct:
        retry:
          enabled: true
          max-attempts: 3
  data:
    mongodb:
      uri: mongodb://admin:admin@jlht.icu:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
      database: debugger_music
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
dubbo:
  config-center:
    address: zookeeper://jlht.icu:2181