spring:
  application:
    name: debug-data
    workerId: 1
    datacenterId: 1
  rabbitmq:
    addresses: 786793.top:5672
    publisher-returns: true
    username: admin
    password: admin
    listener:
      direct:
        retry:
          enabled: true
          max-attempts: 3
      simple:
        concurrency: 9
        max-concurrency: 20
  data:
    mongodb:
      uri: mongodb://admin:admin@jlht.icu:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
      database: debugger_music
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  aop:
    auto: true
    proxy-target-class: true
dubbo:
  config-center:
    address: zookeeper://786793.top:2181