version: "3.7"
services:
  mysql:
    #bind-address=0.0.0.0
    #firewall-cmd --zone=public --add-port=80/tcp --permanent
    #firewall-cmd --reload
    image: mysql
    container_name: mysql
    expose:
      - 3306
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    privileged: "true"
    volumes:
    - /docker-data/mysql/my.cnf:/etc/mysql/my.cnf
    - /docker-data/mysql/lib:/var/lib/mysql
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
    - 6379:6379
  zookeeper:
    image: zookeeper
    container_name: zookeeper

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    expose:
      - 5672
    ports:
    - 5672:5672
  rabbitmq-management:
    image: rabbitmq:3-management
    container_name: rabbitmq-management
    links:
      - rabbitmq
    ports:
      - 15672:15672
    environment:
      - "RABBITMQ_DEFAULT_USER=dalong"
      - "RABBITMQ_DEFAULT_PASS=dalong"


