spring:
  application:
    name: server-music
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://jlht.icu:3306/orange_music
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
     filter:
       log4j2:
         enabled: true
         statement-create-after-log-enabled: false
         statement-close-after-log-enabled: false
         result-set-close-after-log-enabled: false
         result-set-open-after-log-enabled: false
         statement-executable-sql-log-enable: true
  aop:
    auto: true
    proxy-target-class: true
mybatis:
  type-aliases-package: cn.fan
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  global-config:
    db-config:
      column-format: "`%s`"
      id-type: auto

dubbo:
  config-center:
    address: zookeeper://786793.top:2181
  application:
    name: server-music
  consumer:
    timeout: