spring:
  application:
    name: server-music
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://786793.top:3306/orange_music
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: cn.fan
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  global-config:
    db-config:
      column-format: "`%s`"
      id-type: auto

dubbo:
  config-center:
    address: zookeeper://786793.top:2181
  application:
    name: server-music