version: "3.7"
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    privileged: true
    volumes:
      - /docker-data/mysql/my.cnf:/etc/mysql/my.cnf
      - /docker-data/mysql/lib:/var/lib/mysql
      - /docker-data/mysql/mysql-files:/var/lib/mysql-files
  shardingsphere-proxy:
    container_name: shardingsphere-proxy
    image: apache/shardingsphere-proxy
    privileged: true
    restart: always
    network_mode: host
    environment:
      - PORT=3308
    volumes:
    - /docker-data/shardingsphere-proxy/conf:/opt/shardingsphere-proxy/conf
    - /docker-data/shardingsphere-proxy/ext-lib:/opt/shardingsphere-proxy/ext-lib
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  zookeeper:
    restart: always
    image: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=admin"
  mangodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - /docker-data/mongodb/db:/data/db
    privileged: true
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  dubbo-admin:
    container_name: dubbo-admin
    image: apache/dubbo-admin:latest
    restart: always
    ports:
      - 9091:8080
    environment:
      - "admin.config-center=zookeeper://786793.top:2181"
  jenkins:
    restart: always
    container_name: jenkins
    image: jenkins/jenkins:jdk11
    ports:
      - 7071:8080

  minio:
    restart: always
    container_name: minio
    image: minio/minio
    ports:
    - 9000:9000
    - 9001:9001
    volumes:
    - /docker-data/minio/data:/data
    - /dokcer-data/minio/config:/root/.minio
    command: server /data --console-address '0.0.0.0:9001'