version: "3.7"
services:
  mysql:
    #bind-address=0.0.0.0
    #firewall-cmd --zone=public --add-port=80/tcp --permanent
    #firewall-cmd --reload
    image: mysql
    container_name: mysql
    expose:
      - 3306
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    privileged: "true"
    volumes:
    - /home/docker-data/mysql/my.cnf:/etc/mysql/my.cnf
    - /home/docker-data/mysql/lib:/var/lib/mysql
  fastdfs_tracker:
    container_name: fastdfs_tracker
    image: season/fastdfs
    network_mode: host
    privileged: true
    volumes:
    - /home/docker-data/fastdfs/tracker/data:/fastdfs/tracker/data
    - /home/docker-data/fastdfs/tracker/client.conf:/etc/fdfs/client.conf
    command: tracker
  fastdfs_storage:
    container_name: fastdfs_storage
    image: season/fastdfs
    network_mode: host
    volumes:
    - /home/docker-data/fastdfs/storage/data:/fastdfs/storage/data
    - /home/docker-data/fastdfs/storage/path:/fastdfs/store_path
    privileged: true
    environment:
      - TRACKER_SERVER=192.168.0.106:22122
    command: storage
  fastdfs_nginx:
    container_name: fastdfs_nginx
    image: season/fastdfs:1.2
    privileged: true
    network_mode: host
    volumes:
    - /home/docker-data/fastdfs/storage/path:/fastdfs/store_path
    - /home/docker-data/fastdfs/nginx/nginx.conf:/etc/nginx/conf/nginx.conf
    environment:
      - TRACKER_SERVER=localhost:22122
    command: nginx
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
    - 6379:6379
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
    - 2181:2181
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=admin"
  mangodb:
    image: mongo
    container_name: mongodb
    ports:
    - 27017:27017
    volumes:
    - /home/docker-data/mongodb/db:/data/db
    privileged: true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  dubbo-admin:
    container_name: dubbo-admin
    image: apache/dubbo-admin
    ports:
    - 9091:8080
    environment:
      - "admin.config-center=zookeeper://jlht.icu:2181"
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:jdk11
    ports:
    - 7071:8080
