package cn.fan.model.music;

import java.io.Serializable;
import java.util.Date;

public class Song implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.id
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.type
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.mid
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.plat_Id
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private Integer platId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.name
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.title
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.sub_title
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private String subTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.album_plat_id
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private Integer albumPlatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.mvid
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private String mvid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.language
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private Integer language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.genre
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private Integer genre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.public_time
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private Date publicTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.price_play
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private Boolean pricePlay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.media_mid
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private String mediaMid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.id
     *
     * @return the value of song.id
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.id
     *
     * @param id the value for song.id
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.type
     *
     * @return the value of song.type
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.type
     *
     * @param type the value for song.type
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.mid
     *
     * @return the value of song.mid
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.mid
     *
     * @param mid the value for song.mid
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.plat_Id
     *
     * @return the value of song.plat_Id
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public Integer getPlatId() {
        return platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.plat_Id
     *
     * @param platId the value for song.plat_Id
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.name
     *
     * @return the value of song.name
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.name
     *
     * @param name the value for song.name
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.title
     *
     * @return the value of song.title
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.title
     *
     * @param title the value for song.title
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.sub_title
     *
     * @return the value of song.sub_title
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.sub_title
     *
     * @param subTitle the value for song.sub_title
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.album_plat_id
     *
     * @return the value of song.album_plat_id
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public Integer getAlbumPlatId() {
        return albumPlatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.album_plat_id
     *
     * @param albumPlatId the value for song.album_plat_id
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setAlbumPlatId(Integer albumPlatId) {
        this.albumPlatId = albumPlatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.mvid
     *
     * @return the value of song.mvid
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public String getMvid() {
        return mvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.mvid
     *
     * @param mvid the value for song.mvid
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setMvid(String mvid) {
        this.mvid = mvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.language
     *
     * @return the value of song.language
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public Integer getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.language
     *
     * @param language the value for song.language
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setLanguage(Integer language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.genre
     *
     * @return the value of song.genre
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public Integer getGenre() {
        return genre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.genre
     *
     * @param genre the value for song.genre
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setGenre(Integer genre) {
        this.genre = genre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.public_time
     *
     * @return the value of song.public_time
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public Date getPublicTime() {
        return publicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.public_time
     *
     * @param publicTime the value for song.public_time
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setPublicTime(Date publicTime) {
        this.publicTime = publicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.price_play
     *
     * @return the value of song.price_play
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public Boolean getPricePlay() {
        return pricePlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.price_play
     *
     * @param pricePlay the value for song.price_play
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setPricePlay(Boolean pricePlay) {
        this.pricePlay = pricePlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.media_mid
     *
     * @return the value of song.media_mid
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public String getMediaMid() {
        return mediaMid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.media_mid
     *
     * @param mediaMid the value for song.media_mid
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setMediaMid(String mediaMid) {
        this.mediaMid = mediaMid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", mid=").append(mid);
        sb.append(", platId=").append(platId);
        sb.append(", name=").append(name);
        sb.append(", title=").append(title);
        sb.append(", subTitle=").append(subTitle);
        sb.append(", albumPlatId=").append(albumPlatId);
        sb.append(", mvid=").append(mvid);
        sb.append(", language=").append(language);
        sb.append(", genre=").append(genre);
        sb.append(", publicTime=").append(publicTime);
        sb.append(", pricePlay=").append(pricePlay);
        sb.append(", mediaMid=").append(mediaMid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}