package cn.fan.dao;

import cn.fan.model.music.Song;
import cn.fan.model.music.SongExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    long countByExample(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    int deleteByExample(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    int insert(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    int insertSelective(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    List<Song> selectByExample(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    Song selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") Song record, @Param("example") SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    int updateByExample(@Param("record") Song record, @Param("example") SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    int updateByPrimaryKeySelective(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    int updateByPrimaryKey(Song record);

    int batchInsert(List<Song> records) {
    }

    int batchInsertSelective(@Param("records") List<Song> records, @Param("columns") String ... columns) {
    }
}