spring:
  application:
    name: server-file
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://r730.host:3308/readwrite_splitting_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 4
  aop:
    auto: true
    proxy-target-class: true
mybatis:
  type-aliases-package: cn.fan
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:
    name: server-file
  config-center:
    address: zookeeper://r730.host:2181
mybatis-plus:
  global-config:
    db-config:
      column-format: "`%s`"
      id-type: auto
minio:
  endpoint: http://r730.host:9000
  access-key: minioadmin
  secret-key: minioadmin
