package cn.fan.model.common;

import java.io.Serializable;

public class Property implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.id
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.entityType
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private String entitytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.key
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.value
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table property
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.id
     *
     * @return the value of property.id
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.id
     *
     * @param id the value for property.id
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.entityType
     *
     * @return the value of property.entityType
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public String getEntitytype() {
        return entitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.entityType
     *
     * @param entitytype the value for property.entityType
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setEntitytype(String entitytype) {
        this.entitytype = entitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.key
     *
     * @return the value of property.key
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.key
     *
     * @param key the value for property.key
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.value
     *
     * @return the value of property.value
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.value
     *
     * @param value the value for property.value
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Sun May 16 22:00:30 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", entitytype=").append(entitytype);
        sb.append(", key=").append(key);
        sb.append(", value=").append(value);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}