dubbo:
  config-center:
    address: zookeeper://786793.top:2181
  application:
    name: server-musicdistributed-lock
spring:
  application:
    name: distributed-lock
  aop:
    auto: true
    proxy-target-class: true